import yanoljaLive from "../assets/video/yanoljaLive.mp4";
import hotelManoah from "../assets/video/hotelManoah.mp4"
import yanoljaESG from "../assets/images/Yanolja_ESG_img_Mobile.png"

export default [
  {
    id: 1,
    name: "자바스크립트 코딩 ex1",
    duration: "7days",
    peoples: "팀프로젝트",
    category: ["HTML5", "CSS3", "JAVASCRIPT"],
    description: "팀 프로젝트로 진행한 야놀자 홈페이지 클론 코딩. ESG페이지 / 로딩 애니메이션 / 푸터 등 작업.",
    video: yanoljaLive,
    img: yanoljaESG,
  },
  {
    id: 2,
    name: "반응형 웹페이지 ex2",
    duration: "7days",
    peoples: "팀프로젝트",
    category: ["HTML5", "CSS3", "JAVASCRIPT"],
    description: "팀 프로젝트로 진행한 야놀자 홈페이지 클론 코딩. ESG페이지 / 로딩 애니메이션 / 푸터 등 작업.",
    video: yanoljaLive,
    img: '#',
  },
  {
    id: 3,
    name: "야놀자 클론 코딩",
    duration: "7days",
    peoples: "팀프로젝트",
    category: ["HTML5", "CSS3", "JAVASCRIPT"],
    description: "팀 프로젝트로 진행한 야놀자 홈페이지 클론 코딩. ESG페이지 / 로딩 애니메이션 / 푸터 등 작업.",
    video: yanoljaLive,
    img: yanoljaESG,
  },
  {
    id: 4,
    name: "호텔 마노아 클론 코딩",
    duration: "7days",
    peoples: "개인프로젝트",
    category: ["REACT", "JAVASCRIPT", "styled-components"],
    description: "cafe24에 있는 호텔 마노아 페이지 REACT로 클론 코딩 / REACT 첫 작업",
    video: hotelManoah,
    img: "#",
  },
  {
    id: 5,
    name: "example5",
    duration: "3days",
    peoples: "개인프로젝트",
    category: ["Ex3", "JAVASCRIPT", "styled-components"],
    description: "프로젝트 예시 5",
    video: "#",
    img: "#",
  },
  {
    id: 6,
    name: "example6",
    duration: "3days",
    peoples: "개인프로젝트",
    category: ["Ex3", "JAVASCRIPT", "styled-components"],
    description: "프로젝트 예시 6",
    video: "#",
    img: "#",
  },
];
